@api=http://localhost:3333
@token= {{authenticate.response.body.access_token}}

###
POST {{api}}/create-account
Content-Type: application/json

{
    "email":"franzhenry@gmail.com",
    "password":"1234567",
    "name":"henry"
}



### 
# @name authenticate
POST {{api}}/sessions
Content-Type: application/json

{
    "email":"franzhenry@gmail.com",
    "password":"1234567"
}

### 
@name = create-todo
POST {{api}}/create-todo
Authorization: Bearer {{token}}
Content-Type: application/json
