@api=http://localhost:3333

POST {{api}}/create-account
Content-Type: application/json

{
    "email":"franzhenry@gmail.com",
    "password":"1234567",
    "name":"henry"
}

###

GET {{api}}/create-account
Content-Type: application/json
