@api=http://localhost:8080
@token= {{authenticate.response.body.access_token}}

###
POST {{api}}/accounts
Content-Type: application/json

{
    "name":"henry franz",
    "email":"examdsadasdasple1@gmail.com",
    "password":"12345678",
}



### 
# @name authenticate
POST {{api}}/sessions
Content-Type: application/json

{
    "email":"franzhenry@gmail.com",
    "password":"1234567"
}

### 
@name = todos
POST {{api}}/todos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "new-todo",
    "description": "new-todo-description",
}