
version: '3.8'

services:
  postgres:
    container_name: postgres-nest-studding 
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: nest-studding
